kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: google/dart
    commands:
      - flutter pub get
      - flutter pub run test
trigger:
  branch:
    - master
  event:
    - push