kind: pipeline
type: kubernetes
name: default

steps:
  - name: test
    image: cirrusci/flutter:stable
    commands:
      - flutter pub get
      - flutter pub run test
trigger:
  branch:
    - master
  event:
    - push