kind: pipeline
type: kubernetes
name: default

steps:
  - name: test
    image: cirrusci/flutter:stable
    commands:
      - flutter pub get
      - flutter pub run test
trigger:
  branch:
    - master
  event:
    - push
---
kind: pipeline
type: kubernetes
name: github-push
steps:
- name: push commit
  image: appleboy/drone-git-push:0.2.0-linux-amd64
  settings:
    branch: master
    remote: git@github.com:broodjeaap/ohthatsa.git
    force: true
    ssh_key:
      from_secret: id_rsa
trigger:
  branch:
  - master
  event:
  - push